export const nigeriaStates = {
  Abia: ["Aba", "Umuahia", "Ohafia"],
  Adamawa: ["Yola", "Mubi", "Numan"],
  AkwaIbom: ["Uyo", "Ikot Ekpene", "Eket"],
  Anambra: ["Awka", "Onitsha", "Nnewi"],
  Bauchi: ["Bauchi", "Azare", "Misau"],
  Bayelsa: ["Yenagoa", "Ogbia", "Brass"],
  Benue: ["Makurdi", "Gboko", "Otukpo"],
  Borno: ["Maiduguri", "Biu", "Dikwa"],
  CrossRiver: ["Calabar", "Ugep", "Ogoja"],
  Delta: ["Asaba", "Warri", "Sapele"],
  Ebonyi: ["Abakaliki", "Afikpo", "Onueke"],
  Edo: ["Benin City", "Auchi", "Uromi"],
  Ekiti: ["Ado-Ekiti", "Ikere-Ekiti", "Ise-Ekiti"],
  Enugu: ["Enugu", "Nsukka", "Awgu"],
  Gombe: ["Gombe", "Kumo", "Dukku"],
  Imo: ["Owerri", "Orlu", "Okigwe"],
  Jigawa: ["Dutse", "Hadejia", "Gumel"],
  Kaduna: ["Kaduna", "Zaria", "Kafanchan"],
  Kano: ["Kano", "Wudil", "Rano"],
  Katsina: ["Katsina", "Daura", "Funtua"],
  Kebbi: ["Birnin Kebbi", "Argungu", "Zuru"],
  Kogi: ["Lokoja", "Anyigba", "Okene"],
  Kwara: ["Ilorin", "Offa", "Jebba"],
  Lagos: ["Lagos", "Ikeja", "Epe"],
  Nasarawa: ["Lafia", "Keffi", "Akwanga"],
  Niger: ["Minna", "Suleja", "Bida"],
  Ogun: ["Abeokuta", "Ijebu-Ode", "Sagamu"],
  Ondo: ["Akure", "Owo", "Ondo"],
  Osun: ["Osogbo", "Ile-Ife", "Ilesa"],
  Oyo: ["Ibadan", "Ogbomosho", "Oyo"],
  Plateau: ["Jos", "Pankshin", "Shendam"],
  Rivers: ["Port Harcourt", "Bonny", "Bori"],
  Sokoto: ["Sokoto", "Tambuwal", "Gwadabawa"],
  Taraba: ["Jalingo", "Wukari", "Bali"],
  Yobe: ["Damaturu", "Potiskum", "Nguru"],
  Zamfara: ["Gusau", "Anka", "Talata Mafara"],
};
